### ISSUE TITLE
Question about 2 div #app

### ISSUE THREAD

**Issue by ii64** [Jamie-Yang/vue3-boilerplate#21]
Hello,  i'm curious about 2 div with same id `#app`
is there any feature related about this? 

the one in `public/index.html`

https://github.com/Jamie-Yang/vue3-boilerplate/blob/8b9c263f58d299f0839d9139ae7e6bcc5c300773/public/index.html#L10

and in `src/App.vue`

https://github.com/Jamie-Yang/vue3-boilerplate/blob/8b9c263f58d299f0839d9139ae7e6bcc5c300773/src/App.vue#L2

**Comment by Jamie-Yang** [comment]
Good point. The `#app` in the `src/App.vue` is no longer needed.
Here is the docs [#mounted-application-does-not-replace-the-element](https://v3.vuejs.org/guide/migration/mount-changes.html#mounted-application-does-not-replace-the-element)
