### ISSUE TITLE
how to get access to env variables inside index.html?

### ISSUE THREAD

**Issue by sprucify** [Jamie-Yang/vue3-boilerplate#33]
I get error  `ReferenceError: VUE_APP_TITLE` is not defined when I use `<%= VUE_APP_TITLE %>` inside public/index.html

**Comment by Jamie-Yang** [comment]
Feature added.
Please see the latest changes. https://github.com/Jamie-Yang/vue3-boilerplate/commit/5417db9f0d81f4cf4ebe0e7194a5665c4b0a6b5a

**Comment by sprucify** [comment]
Thanks a lot.
You are definitely a webpack expert.
Any chance you have a look at the other issue about PWA implementation?

I can not figure out how to generate manifest.json. This is normally done via vue-config.js and running vue-cli-service
