### ISSUE TITLE
thread-loader prevents composition api components being included in production bundles

### ISSUE THREAD

**Issue by ItsOnlyBinary** [Jamie-Yang/vue3-boilerplate#41]
I've used this project as inspiration for my own webpack configs. In doing so I found that vue components written in Composition API where not being included in production bundles.

After some investigation it turned out to be caused by 'thread-loader' being used for js files.

**Comment by Jamie-Yang** [comment]
Hey, can you still reproduce this issue?
I tried out a few parent-child combinations and didn't run into any problems with bundling the Composition API components.

**Comment by ItsOnlyBinary** [comment]
Sorry forgot to reply to this. It does seem this has been fixed upstream in thread-loader. Suspect it must have been its interaction with babel which I use to translate my modules to commonjs as it allows me to runtime replace components (have app plugins).
